### ISSUE TITLE
What is the `umask 002` command

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/mindcontrol#1]
I got this error:

```
Traceback (most recent call last):
  File "start_singularity_mindcontrol.py", line 626, in <module>
    raise Exception("This command must be run with a umask of 2, run"
Exception: This command must be run with a umask of 2, run 'umask 002' to set the umask then try this command again
```

I ran `umask 002` as the exception suggests, and it fixed the problem. But this is probably worth documenting in the installation instructions (or making part of the setup script?)

**Comment by Shotgunosine** [comment]
The umask command sets the default permissions mask. This is a good explanation: https://askubuntu.com/a/44548

**Comment by KirstieJane** [comment]
Thanks @Shotgunosine!! Added to the [README](https://github.com/KirstieJane/mindcontrol/blob/master/README.md)
